"use client";

import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import { useScrollAnimation } from "../utils/useScrollAnimation";

const API_BASE = process.env.NEXT_PUBLIC_API_URL || "http://localhost:5000";
const categories = ["All Photos", "International Tours", "Domestic Tours", "Happy Travelers", "Group Tours", "Events & Celebrations", "Behind the Scenes", "Team Moments"];
const mediaUrl = (value) => {
  if (!value) return "";
  if (value.startsWith("http://") || value.startsWith("https://")) return value;
  if (value.startsWith("/uploads/")) return `${API_BASE}${value}`;
  return value;
};
const videoEmbed = (value = "") => { try { const url = new URL(value); if (url.hostname.includes("youtu.be")) return `https://www.youtube.com/embed/${url.pathname.slice(1)}`; if (url.hostname.includes("youtube.com")) return `https://www.youtube.com/embed/${url.searchParams.get("v")}`; if (url.hostname.includes("vimeo.com")) return `https://player.vimeo.com/video/${url.pathname.split("/").filter(Boolean).pop()}`; } catch {} return ""; };
const niceDate = (value, yearOnly = false) => value ? new Intl.DateTimeFormat("en-IN", yearOnly ? { year: "numeric" } : { day: "numeric", month: "short", year: "numeric" }).format(new Date(value)) : "";

function EmptyState({ title, text }) { return <div className="kg-empty"><i className="ti-image" /><h3>{title}</h3><p>{text}</p></div>; }

export default function GalleryExperience() {
  const [data, setData] = useState(null);
  const [error, setError] = useState("");
  const [filter, setFilter] = useState("All Photos");
  const [visible, setVisible] = useState(9);
  const [lightbox, setLightbox] = useState(-1);
  const load = useCallback(async () => { setError(""); try { const response = await fetch(`${API_BASE}/api/gallery`, { cache: "no-store" }); if (!response.ok) throw new Error("Gallery is temporarily unavailable"); setData(await response.json()); } catch (e) { setError(e.message); } }, []);
  useEffect(() => { let active = true; fetch(`${API_BASE}/api/gallery`, { cache: "no-store" }).then((response) => { if (!response.ok) throw new Error("Gallery is temporarily unavailable"); return response.json(); }).then((body) => { if (active) setData(body); }).catch((e) => { if (active) setError(e.message); }); return () => { active = false; }; }, []);
  const photos = useMemo(() => (data?.media || []).filter((item) => item.mediaType === "image" && (filter === "All Photos" || item.category === filter)), [data, filter]);
  const videos = useMemo(() => (data?.media || []).filter((item) => item.mediaType === "video"), [data]);
  const settings = data?.settings || {};
  const shownCategories = settings.visibleCategories?.length ? categories.filter((item) => item === "All Photos" || settings.visibleCategories.includes(item)) : categories;
  useEffect(() => { if (lightbox < 0) return; const key = (event) => { if (event.key === "Escape") setLightbox(-1); if (event.key === "ArrowRight") setLightbox((lightbox + 1) % photos.length); if (event.key === "ArrowLeft") setLightbox((lightbox - 1 + photos.length) % photos.length); }; document.addEventListener("keydown", key); document.body.style.overflow = "hidden"; return () => { document.removeEventListener("keydown", key); document.body.style.overflow = ""; }; }, [lightbox, photos.length]);
  useScrollAnimation([data, filter, visible]);
  if (error) return <main className="kg-page"><section className="kg-error"><h1>We couldn’t load the gallery.</h1><p>{error}</p><button onClick={load}>Try again</button></section></main>;
  return <main className="kg-page">
    <header className="kg-hero">
      {settings.heroImage && <img className="kg-hero-photo" src={mediaUrl(settings.heroImage)} alt="Karnish Tourism travel collection" />}
      <div className="container kg-hero-inner ksa-fade-up"><nav aria-label="Breadcrumb"><Link href="/">Home</Link><span>→</span><span>Gallery</span></nav><p className="kg-eyebrow">Karnish Tourism</p><h1>{settings.heroTitle || "Our Journey in Frames"}</h1><p>{settings.heroSubtitle || "Explore unforgettable memories, remarkable milestones, and beautiful destinations with Karnish Tourism."}</p></div>
    </header>
    {settings.sectionVisibility?.photos !== false && <section className="kg-section"><div className="container"><div className="kg-heading"><p className="kg-eyebrow">Stories in every frame</p><h2>Explore Our Gallery</h2></div><div className="kg-filters" role="tablist" aria-label="Gallery categories">{shownCategories.map((category) => <button key={category} role="tab" aria-selected={filter === category} className={filter === category ? "active" : ""} onClick={() => setFilter(category)}>{category}</button>)}</div>{!data ? <div className="kg-loading-grid">{Array.from({ length: 8 }, (_, i) => <span key={i} />)}</div> : photos.length ? <><div className="kg-masonry">{photos.slice(0, visible).map((photo, index) => <button className="kg-photo" key={photo._id} onClick={() => setLightbox(index)}><img src={mediaUrl(photo.mediaUrl)} alt={photo.description || photo.title} loading="lazy" /><span><b>{photo.title}</b><small>{[photo.destination, niceDate(photo.eventDate)].filter(Boolean).join(" · ")}</small></span></button>)}</div>{visible < photos.length && <button className="kg-outline-button" onClick={() => setVisible((n) => n + 9)}>Load More</button>}</> : <EmptyState title="Memories are being curated" text="Published photographs will appear here as soon as our team adds them." />}</div></section>}
    {settings.sectionVisibility?.achievements !== false && <section className="kg-section kg-tint"><div className="container"><div className="kg-heading"><p className="kg-eyebrow">Earned, verified, celebrated</p><h2>Our Achievements</h2></div>{data?.achievements?.length ? <div className="kg-card-grid">{data.achievements.map((item) => <article className="kg-achievement" key={item._id}>{item.mediaUrl && <img src={mediaUrl(item.mediaUrl)} alt={item.title} loading="lazy" />}<div><span>{item.year || item.category}</span><h3>{item.title}</h3><p>{item.description}</p><small>Issued by {item.issuingOrganization}</small>{item.verificationUrl && <a href={item.verificationUrl} target="_blank" rel="noreferrer">Verify recognition ↗</a>}</div></article>)}</div> : <EmptyState title="No published achievements yet" text="Only genuine, admin-verified recognitions are shown here." />}</div></section>}
    {settings.sectionVisibility?.memories !== false && <section className="kg-section"><div className="container"><div className="kg-heading"><p className="kg-eyebrow">Unforgettable journeys</p><h2>Our Travel Memories</h2></div>{data?.memories?.length ? <div className="kg-memory-grid">{data.memories.map((item) => <article className="kg-memory" key={item._id}>{item.mediaUrls?.[0] && <img src={mediaUrl(item.mediaUrls[0])} alt={item.title} loading="lazy" />}<div><small>{item.destination} · {niceDate(item.travelDate)}</small><h3>{item.title}</h3><p>{item.description}</p>{item.testimonial && <blockquote>“{item.testimonial}”</blockquote>}</div></article>)}</div> : <EmptyState title="Travel stories coming soon" text="Published tour memories will be collected here." />}</div></section>}
    {settings.sectionVisibility?.milestones !== false && <section className="kg-section kg-dark"><div className="container"><div className="kg-heading"><p className="kg-eyebrow">Growing with every journey</p><h2>Our Journey & Milestones</h2></div>{data?.milestones?.length ? <div className="kg-timeline">{data.milestones.map((item) => <article key={item._id}><time>{niceDate(item.milestoneDate, true)}</time><div><small>{item.category}</small><h3>{item.title}</h3><p>{item.description}</p></div></article>)}</div> : <EmptyState title="Our timeline is being prepared" text="Company milestones will appear here after publication." />}</div></section>}
    {settings.sectionVisibility?.videos !== false && <section className="kg-section"><div className="container"><div className="kg-heading"><p className="kg-eyebrow">Watch the adventure</p><h2>Videos & Highlights</h2></div>{videos.length ? <div className="kg-video-grid">{videos.map((item) => <article key={item._id}>{videoEmbed(item.mediaUrl) ? <iframe src={videoEmbed(item.mediaUrl)} title={item.title} loading="lazy" allow="accelerometer; autoplay; encrypted-media; picture-in-picture" allowFullScreen style={{ width: "100%", aspectRatio: "16/9", border: 0, borderRadius: 15 }} /> : <video controls preload="metadata" poster={mediaUrl(item.thumbnailUrl)}><source src={mediaUrl(item.mediaUrl)} /></video>}<h3>{item.title}</h3><p>{item.description}</p></article>)}</div> : <EmptyState title="Highlights are on the way" text="Published destination films and tour reels will appear here." />}</div></section>}
    <section className="kg-cta ksa-scale-up"><div className="container"><p className="kg-eyebrow">Write the next chapter</p><h2>Your Next Adventure Could Be Our Next Memory</h2><div><Link href="/tours" className="kg-primary-button">Explore Tours</Link><Link href="/contact" className="kg-secondary-button">Contact Us</Link></div></div></section>
    {lightbox >= 0 && photos[lightbox] && <div className="kg-lightbox" role="dialog" aria-modal="true" aria-label={photos[lightbox].title} onClick={() => setLightbox(-1)}><button className="kg-close" onClick={() => setLightbox(-1)} aria-label="Close lightbox">×</button><button className="kg-prev" onClick={(e) => { e.stopPropagation(); setLightbox((lightbox - 1 + photos.length) % photos.length); }} aria-label="Previous photo">‹</button><figure onClick={(e) => e.stopPropagation()}><img src={mediaUrl(photos[lightbox].mediaUrl)} alt={photos[lightbox].description || photos[lightbox].title} /><figcaption><b>{photos[lightbox].title}</b><span>{photos[lightbox].description}</span></figcaption></figure><button className="kg-next" onClick={(e) => { e.stopPropagation(); setLightbox((lightbox + 1) % photos.length); }} aria-label="Next photo">›</button></div>}
  </main>;
}
