import Image from "next/image";
import PackageBrowser from "./PackageBrowser";
import DestinationGallery from "./DestinationGallery";
import InquiryForm from "./InquiryForm";
import { RememberViewed } from "./RecentlyViewed";
import { formatPrice } from "../data";

export default function DestinationDetails({ destination }) {
  const info = [["ti-calendar", "Best time", destination.bestTime],["ti-time", "Ideal duration", destination.duration],["ti-money", "Currency", destination.currency],["ti-comments", "Language", destination.language],["ti-id-badge", "Visa", destination.visa],["ti-shine", "Ideal for", destination.idealFor.join(", ")]];
  const faqSchema = { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: destination.faqs.map(item => ({ "@type": "Question", name: item.q, acceptedAnswer: { "@type": "Answer", text: item.a } })) };
  return <main><RememberViewed id={destination.id} /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema).replaceAll("<", "\\u003c") }} />
    <header className="ktours-destination-hero"><Image src={destination.image} alt={`${destination.name} destination`} fill sizes="100vw" preload /><div className="ktours-hero-shade" /><div className="container"><nav aria-label="Breadcrumb"><a href="/tours">Tours</a><i className="ti-angle-right" /><a href={`/tours/${destination.type}`}>{destination.type}</a><i className="ti-angle-right" /><span>{destination.name}</span></nav><div className="ktours-kicker"><span /> {destination.country}</div><h1>{destination.name}</h1><p>{destination.tagline}</p><div className="ktours-destination-stats"><span><small>Packages from</small><strong>{formatPrice(destination.startingPrice)}</strong></span><span><small>Recommended</small><strong>{destination.duration}</strong></span><span><small>Best season</small><strong>{destination.bestTime}</strong></span><span><small>Visa</small><strong>{destination.visa}</strong></span></div><div className="ktours-hero-actions"><a className="ktours-button" href="#packages">View packages <i className="ti-arrow-down" /></a><a className="ktours-button ktours-button-light" href={`/tours/inquiry?destination=${destination.slug}`}>Get custom quote</a></div></div></header>
    <section className="ktours-quick-info container" aria-label="Destination information">{info.map(([icon,label,value]) => <article key={label}><i className={icon} /><div><small>{label}</small><strong>{value}</strong></div></article>)}</section>
    <section className="ktours-section container ktours-overview"><div><div className="ktours-kicker dark"><span /> Discover {destination.name}</div><h2>A journey with character at every turn.</h2></div><div><p>{destination.overview}</p><details><summary>Read more</summary><p>From local culture and regional cuisine to well-paced landmark visits, each itinerary is designed to help you connect with the destination—not simply pass through it. Travel requirements can change, so our specialists confirm current guidance before booking.</p></details></div></section>
    <section className="ktours-highlights"><div className="container"><div className="ktours-heading-row"><div><div className="ktours-kicker dark"><span /> Signature experiences</div><h2>Highlights of {destination.name}</h2></div></div><div className="ktours-highlight-grid">{destination.highlights.map((item, index) => <article key={item.title}><div><Image src={item.image} alt={item.title} fill sizes="(max-width: 800px) 80vw, 25vw" /></div><span>0{index + 1}</span><h3>{item.title}</h3><p>{item.description}</p></article>)}</div></div></section>
    <section className="ktours-section container" id="packages"><div className="ktours-heading-row"><div><div className="ktours-kicker dark"><span /> Choose your journey</div><h2>Available {destination.name} packages</h2><p>Compare durations, stays, inclusions and prices without the guesswork.</p></div><span className="ktours-package-count">{destination.packages.length} packages available</span></div><PackageBrowser destination={destination} /></section>
    <section className="ktours-section container"><div className="ktours-heading-row"><div><div className="ktours-kicker dark"><span /> A closer look</div><h2>Picture yourself in {destination.name}</h2></div></div><DestinationGallery destination={destination} /></section>
    <section className="ktours-why"><div className="container"><div><div className="ktours-kicker"><span /> The experience</div><h2>Why visit {destination.name}?</h2><p>{destination.tagline} We shape each trip to leave room for the moments you will remember most.</p></div><div>{destination.whyVisit.map((item, index) => <article key={item}><span>0{index + 1}</span><h3>{item}</h3></article>)}</div></div></section>
    <section className="ktours-section container ktours-season-section"><div><div className="ktours-kicker dark"><span /> Plan the right moment</div><h2>Best time to visit</h2><p>Seasonality is part of the experience. Use this guide as a starting point; exact weather varies.</p></div><div className="ktours-seasons">{destination.seasons.map(item => <article className={item.tone} key={item.label}><span>{item.months}</span><strong>{item.label}</strong></article>)}</div></section>
    <section className="ktours-section container ktours-faq"><div><div className="ktours-kicker dark"><span /> Good to know</div><h2>Frequently asked questions</h2><p>Quick answers for planning your {destination.name} holiday.</p></div><div>{destination.faqs.map(item => <details key={item.q}><summary>{item.q}<i className="ti-plus" /></summary><p>{item.a}</p></details>)}</div></section>
    <section className="ktours-section container ktours-inquiry-wrap"><div className="ktours-inquiry-intro"><div className="ktours-kicker dark"><span /> Make it personal</div><h2>Build your {destination.name} holiday.</h2><p>Tell us your dates, people and preferences. We’ll tailor the details and send a clear quote.</p></div><InquiryForm condensed defaultDestination={destination.slug} /></section>
  </main>;
}
