"use client";

import { useMemo, useState } from "react";
import Image from "next/image";
import { formatPrice } from "../data";

export default function PackageBrowser({ destination }) {
  const [budget, setBudget] = useState("all");
  const [duration, setDuration] = useState("all");
  const [category, setCategory] = useState("all");
  const [selected, setSelected] = useState([]);
  const [showCompare, setShowCompare] = useState(false);
  const filtered = useMemo(() => destination.packages.filter((item) => (budget === "all" || item.salePrice <= Number(budget)) && (duration === "all" || item.days <= Number(duration)) && (category === "all" || item.category === category)), [destination, budget, duration, category]);
  function toggle(item) {
    setSelected((current) => current.includes(item.id) ? current.filter((id) => id !== item.id) : current.length < 3 ? [...current, item.id] : current);
  }
  const compared = destination.packages.filter((item) => selected.includes(item.id));
  return <>
    <div className="ktours-package-tools"><div><label><span>Budget</span><select value={budget} onChange={(e) => setBudget(e.target.value)}><option value="all">Any budget</option><option value={destination.startingPrice + 10000}>Best value</option><option value={destination.startingPrice + 40000}>Up to {formatPrice(destination.startingPrice + 40000)}</option></select></label><label><span>Duration</span><select value={duration} onChange={(e) => setDuration(e.target.value)}><option value="all">Any duration</option><option value="5">Up to 5 days</option><option value="7">Up to 7 days</option><option value="10">Up to 10 days</option></select></label><label><span>Package type</span><select value={category} onChange={(e) => setCategory(e.target.value)}><option value="all">All styles</option><option>Budget</option><option>Family</option><option>Luxury</option></select></label></div>{(budget !== "all" || duration !== "all" || category !== "all") && <button onClick={() => { setBudget("all"); setDuration("all"); setCategory("all"); }}>Clear all filters</button>}</div>
    <div className="ktours-package-list">{filtered.map((item) => <article className="ktours-package-card" key={item.id}><div className="ktours-package-image"><Image src={item.image} alt={item.name} fill sizes="(max-width: 900px) 100vw, 380px" /><span>{Math.round((1 - item.salePrice / item.originalPrice) * 100)}% off</span><button type="button" className="ktours-save-package" aria-label={`Save ${item.name}`} onClick={() => { try { const saved = JSON.parse(localStorage.getItem("karnish-saved-tours") || "[]"); localStorage.setItem("karnish-saved-tours", JSON.stringify(saved.includes(item.id) ? saved.filter(id => id !== item.id) : [...saved, item.id])); } catch {} }}><i className="ti-heart" /></button></div><div className="ktours-package-main"><div className="ktours-package-title"><div><span>{destination.name} · {item.category}</span><h3>{item.name}</h3></div><b><i className="fa-solid fa-star" /> {item.rating} <small>({item.reviews})</small></b></div><div className="ktours-package-meta"><span><i className="ti-calendar" /> {item.days} days / {item.nights} nights</span><span><i className="ti-location-pin" /> {item.cities.join(", ")}</span><span><i className="ti-home" /> {item.hotel}</span></div><div className="ktours-inclusion-row">{[["ti-home", "Hotel"],["ti-cup", "Breakfast"],["ti-car", "Transfers"],["ti-camera", "Sightseeing"]].map(([icon, label]) => <span key={label}><i className={icon} />{label}</span>)}</div><div className="ktours-package-bottom"><label><input type="checkbox" checked={selected.includes(item.id)} onChange={() => toggle(item)} disabled={!selected.includes(item.id) && selected.length >= 3} /> Compare</label><div className="ktours-price"><small><s>{formatPrice(item.originalPrice)}</s> Starting from</small><strong>{formatPrice(item.salePrice)}</strong><span>/ person</span></div><div className="ktours-package-actions"><a href={`/tours/inquiry?destination=${destination.slug}&package=${encodeURIComponent(item.name)}`} className="outline">Get quote</a><a href={`/tours/${destination.type}/${destination.slug}/${item.slug}`}>View details <i className="ti-arrow-right" /></a></div></div></div></article>)}</div>
    {!filtered.length && <div className="ktours-empty"><i className="ti-filter" /><h3>No packages match those filters</h3><p>Clear your filters to see all available stays.</p></div>}
    {selected.length > 0 && <div className="ktours-compare-bar"><div><span>{selected.length}</span><p><strong>{selected.length} package{selected.length > 1 ? "s" : ""} selected</strong><small>Select up to 3 to compare</small></p></div><button onClick={() => setSelected([])}>Clear</button><button className="ktours-button" onClick={() => setShowCompare(true)} disabled={selected.length < 2}>Compare packages</button></div>}
    {showCompare && <div className="ktours-dialog-backdrop" role="presentation" onMouseDown={() => setShowCompare(false)}><section className="ktours-compare-dialog" role="dialog" aria-modal="true" aria-label="Compare packages" onMouseDown={e => e.stopPropagation()}><button className="ktours-dialog-close" onClick={() => setShowCompare(false)} aria-label="Close comparison"><i className="ti-close" /></button><div className="ktours-heading-row"><div><div className="ktours-kicker dark"><span /> Side by side</div><h2>Compare packages</h2></div></div><div className="ktours-compare-scroll"><table><thead><tr><th>Package</th>{compared.map(item => <th key={item.id}>{item.name}<strong>{formatPrice(item.salePrice)}</strong></th>)}</tr></thead><tbody>{[["Duration", item => `${item.days} days / ${item.nights} nights`],["Hotel", item => item.hotel],["Meals", item => item.meals],["Transfers", item => item.transfers],["Sightseeing", item => item.sightseeing],["Activities", item => item.activities.join(", ")],["Cancellation", item => item.cancellation]].map(([label, value]) => <tr key={label}><th>{label}</th>{compared.map(item => <td key={item.id}>{value(item)}</td>)}</tr>)}</tbody></table></div></section></div>}
  </>;
}
