"use client";

import { useEffect, useState } from "react";
import Image from "next/image";
import { formatPrice } from "../data";
import InquiryForm from "./InquiryForm";

export default function PackageDetails({ destination, tourPackage, similar }) {
  const [openDay, setOpenDay] = useState(0);
  const [showQuote, setShowQuote] = useState(false);
  useEffect(() => { try { const key = "karnish-recent-packages"; const value = JSON.parse(localStorage.getItem(key) || "[]"); localStorage.setItem(key, JSON.stringify([tourPackage.id, ...value.filter(id => id !== tourPackage.id)].slice(0, 6))); } catch {} }, [tourPackage.id]);
  const packageImages = Array.isArray(tourPackage.images) && tourPackage.images.length > 0 ? tourPackage.images : [tourPackage.image || destination.image || "/images/destination-01.jpg"];
  const packageCities = Array.isArray(tourPackage.cities) && tourPackage.cities.length > 0 ? tourPackage.cities : [destination.name];
  const packageActivities = Array.isArray(tourPackage.activities) && tourPackage.activities.length > 0 ? tourPackage.activities : Array.isArray(tourPackage.inclusions) && tourPackage.inclusions.length > 0 ? tourPackage.inclusions : ["Curated Local Tour", "Guided Discovery", "Scenic Sightseeing"];
  const packageInclusions = Array.isArray(tourPackage.inclusions) ? tourPackage.inclusions : ["Accommodation", "Airport transfers", "Guided sightseeing"];
  const packageExclusions = Array.isArray(tourPackage.exclusions) ? tourPackage.exclusions : ["International flights", "Personal expenses", "Travel insurance"];
  const packageItinerary = Array.isArray(tourPackage.itinerary) ? tourPackage.itinerary : [];

  return <main>
    <header className="ktours-package-hero"><div className="container"><nav aria-label="Breadcrumb"><a href="/tours">Tours</a><i className="ti-angle-right" /><a href={`/tours/${destination.type}/${destination.slug}`}>{destination.name}</a><i className="ti-angle-right" /><span>{tourPackage.name}</span></nav><div className="ktours-package-hero-grid"><div><div className="ktours-kicker dark"><span /> {destination.country} · {tourPackage.category || "Signature"}</div><h1>{tourPackage.name}</h1><div className="ktours-package-hero-meta"><span><i className="ti-calendar" /> {tourPackage.days || 5} days / {tourPackage.nights || 4} nights</span><span><i className="ti-location-pin" /> {packageCities.join(", ")}</span><span><i className="fa-solid fa-star" /> {tourPackage.rating || 4.9} ({tourPackage.reviews || 24} reviews)</span></div></div><div className="ktours-hero-price"><small>Starting from</small><strong>{formatPrice(tourPackage.salePrice || destination.startingPrice || 39999)}</strong><span>/ person</span><button className="ktours-button" onClick={() => setShowQuote(true)}>Get quote <i className="ti-arrow-right" /></button></div></div><div className="ktours-package-mosaic">{packageImages.map((image, index) => <div key={image} className={index === 0 ? "featured" : ""}><Image src={image} alt={`${tourPackage.name} view ${index + 1}`} fill sizes={index === 0 ? "70vw" : "30vw"} preload={index === 0} /></div>)}</div></div></header>
    <section className="ktours-package-anchor"><div className="container"><a href="#overview">Overview</a><a href="#itinerary">Itinerary</a><a href="#hotel">Hotel</a><a href="#inclusions">Inclusions</a><a href="#information">Important info</a></div></section>
    <div className="container ktours-details-layout"><div>
      <section className="ktours-detail-section" id="overview"><div className="ktours-kicker dark"><span /> Your journey at a glance</div><h2>Package highlights</h2><div className="ktours-benefit-grid">{packageActivities.map((activity, index) => <article key={`act-${index}`}><span>0{index + 1}</span><h3>{activity}</h3><p>Included in your thoughtfully paced itinerary.</p></article>)}</div></section>
      <section className="ktours-detail-section" id="itinerary"><div className="ktours-kicker dark"><span /> Day by day</div><h2>Your itinerary</h2><div className="ktours-timeline">{packageItinerary.map((day, index) => <article className={openDay === index ? "open" : ""} key={day.day || index}><button onClick={() => setOpenDay(openDay === index ? -1 : index)} aria-expanded={openDay === index}><span>Day {day.day || index + 1}</span><strong>{day.title}</strong><i className="ti-plus" /></button>{openDay === index && <p>{day.description}</p>}</article>)}</div></section>
      <section className="ktours-detail-section" id="hotel"><div className="ktours-kicker dark"><span /> Rest well</div><h2>Your hotel</h2><div className="ktours-hotel-card"><div><i className="ti-home" /></div><section><span>{tourPackage.hotelRating || 4} star accommodation</span><h3>{tourPackage.hotel || "4-Star Handpicked Stay"}</h3><p>{tourPackage.roomType || "Deluxe Room"} · {tourPackage.nights || 4} nights · {tourPackage.meals || "Daily Breakfast"}</p><small>Final hotel name is confirmed at booking or replaced with a similar-category stay.</small></section></div></section>
      <section className="ktours-detail-section" id="inclusions"><div className="ktours-kicker dark"><span /> The clear details</div><h2>What’s included</h2><div className="ktours-include-columns"><div>{packageInclusions.map((item, i) => <p key={`inc-${i}`}><i className="ti-check" /> {item}</p>)}</div><div><h3>Not included</h3>{packageExclusions.map((item, i) => <p key={`exc-${i}`}><i className="ti-minus" /> {item}</p>)}</div></div></section>
      <section className="ktours-detail-section" id="information"><div className="ktours-kicker dark"><span /> Before you book</div><h2>Important information</h2>{[["Cancellation policy", tourPackage.cancellation || "Standard flexible policy"],["Payment terms", "A booking deposit secures the package. Milestone dates are shared in your quote."],["Visa information", destination.visa || "Visa guidance provided by consular desk"],["Travel requirements", "Valid government ID/passport and destination-specific documentation are required."],["Child policy", "Child rates depend on age, room sharing and selected activities."]].map(([title,text]) => <details key={title}><summary>{title}<i className="ti-plus" /></summary><p>{text}</p></details>)}</section>
    </div><aside className="ktours-sticky-quote"><span>Package price</span><div><s>{formatPrice(tourPackage.originalPrice)}</s><strong>{formatPrice(tourPackage.salePrice)}</strong><small>per person</small></div><p><i className="ti-check" /> Best-price itinerary assistance</p><p><i className="ti-check" /> Flexible customisation</p><p><i className="ti-check" /> Dedicated travel support</p><button className="ktours-button" onClick={() => setShowQuote(true)}>Get quote <i className="ti-arrow-right" /></button><a href="/contact"><i className="ti-headphone-alt" /> Talk to a specialist</a></aside></div>
    <section className="ktours-section container"><div className="ktours-heading-row"><div><div className="ktours-kicker dark"><span /> More ways to travel</div><h2>You may also like</h2></div></div><div className="ktours-similar-grid">{similar.map(item => <a key={item.id} href={`/tours/${destination.type}/${destination.slug}/${item.slug}`}><div><Image src={item.image} alt={item.name} fill sizes="360px" /></div><span>{item.days} days · {item.category}</span><h3>{item.name}</h3><p>From <strong>{formatPrice(item.salePrice)}</strong><i className="ti-arrow-right" /></p></a>)}</div></section>
    <div className="ktours-mobile-cta"><div><small>From</small><strong>{formatPrice(tourPackage.salePrice)}</strong></div><button onClick={() => setShowQuote(true)}>Get quote</button></div>
    {showQuote && <div className="ktours-dialog-backdrop" onMouseDown={() => setShowQuote(false)}><section className="ktours-quote-dialog" role="dialog" aria-modal="true" aria-label="Get a package quote" onMouseDown={e => e.stopPropagation()}><button className="ktours-dialog-close" onClick={() => setShowQuote(false)} aria-label="Close"><i className="ti-close" /></button><div className="ktours-kicker dark"><span /> Personalise this trip</div><h2>Get a quote for {tourPackage.name}</h2><InquiryForm condensed defaultDestination={destination.slug} defaultPackage={tourPackage.name} /></section></div>}
  </main>;
}
