const models = {
  destinations: require("../models/Destination"),
  tours: require("../models/TourPackage"),
  packages: require("../models/TourPackage"),
  activities: require("../models/Activity"),
  hotels: require("../models/Hotel"),
  bookings: require("../models/Booking"),
  inquiries: require("../models/Inquiry"),
  payments: require("../models/Payment"),
  reviews: require("../models/Review"),
  testimonials: require("../models/Review"),
  offers: require("../models/Offer"),
  coupons: require("../models/Coupon"),
  posts: require("../models/Post"),
  blogs: require("../models/Post"),
  customers: require("../models/User"),
  collaborators: require("../models/User"),
  users: require("../models/User"),
  organizations: require("../models/Organization"),
  commissions: require("../models/Commission"),
  auditlogs: require("../models/AuditLog"),
  visas: require("../models/Visa"),
  sitecontent: require("../models/SiteContent"),
  banners: require("../models/Banner"),
  notifications: require("../models/Notification"),
};

const publicResources = new Set([
  "destinations",
  "tours",
  "packages",
  "activities",
  "hotels",
  "offers",
  "reviews",
  "testimonials",
  "posts",
  "blogs",
  "visas",
  "sitecontent",
  "banners",
]);

module.exports = { models, publicResources };
