const ALL_VISA_DESTINATIONS = [
  {
    slug: "uae",
    alias: ["dubai"],
    country: "United Arab Emirates",
    title: "UAE (Dubai) Tourist & Visit Visa",
    region: "Middle East",
    flag: "🇦🇪",
    image: "/images/destination-01.jpg",
    badge: "Fast Track 24h Available",
    tagline: "Instant online e-Visa processing for tourism, family visits, and business stopovers in Dubai & Abu Dhabi.",
    startingPrice: 6899,
    startingPriceAED: 310,
    processingTime: "24 – 48 Hours",
    validity: "60 Days from issue",
    stayPeriod: "30 or 60 Days",
    entryType: "Single & Multiple Entry",
    approvalRate: "99.6%",
    expressAvailable: true,
    expressTime: "4 – 8 Hours",
    types: [
      {
        id: "uae-30-single",
        name: "30 Days Tourist Visa (Single Entry)",
        validity: "60 Days",
        stay: "30 Days",
        fee: 6899,
        expressFee: 8999,
        description: "Best for short leisure holidays, shopping festivals, and city stopovers.",
      },
      {
        id: "uae-60-single",
        name: "60 Days Tourist Visa (Single Entry)",
        validity: "60 Days",
        stay: "60 Days",
        fee: 12499,
        expressFee: 14999,
        description: "Ideal for extended vacations, family reunions, and property inspection visits.",
      },
      {
        id: "uae-30-multiple",
        name: "30 Days Multiple Entry Visa",
        validity: "60 Days",
        stay: "30 Days per trip",
        fee: 14200,
        expressFee: 16800,
        description: "Perfect for frequent business travelers and cruise passengers visiting neighboring GCC states.",
      },
      {
        id: "uae-60-multiple",
        name: "60 Days Multiple Entry Visa",
        validity: "60 Days",
        stay: "60 Days flexible",
        fee: 18900,
        expressFee: 21500,
        description: "Maximum flexibility for multi-city business, consultancy, and extended family stays.",
      },
    ],
    eligibility: [
      "Valid passport with minimum 6 months validity from departure date.",
      "Clear front & back bio-page scans without reflections or glare.",
      "Confirmed onward or return flight booking.",
      "Confirmed hotel reservation or host residence address in the UAE.",
      "Minor travelers (under 18) must travel with parent or submit parental consent letter.",
    ],
    documents: [
      {
        category: "Mandatory Identification",
        items: [
          "Color scan of passport first and last pages (minimum 6 months validity).",
          "Recent passport-size photograph on plain white background (no glasses, neutral expression).",
          "PAN card copy (for Indian nationals).",
        ],
      },
      {
        category: "Travel & Stay Proof",
        items: [
          "Confirmed return or onward flight itinerary.",
          "Hotel booking confirmation or UAE resident host's Emirates ID and tenancy contract.",
        ],
      },
      {
        category: "Optional / For Minors",
        items: [
          "Birth certificate copy in English for travelers below 18 years.",
          "Parent passport and visa copies if minor is traveling alone or with one parent.",
        ],
      },
    ],
    steps: [
      { step: 1, title: "Online Application", desc: "Select your visa duration, fill traveler details, and upload clear document scans." },
      { step: 2, title: "Expert Document Audit", desc: "Our certified visa team reviews passport clarity, photo dimensions, and file compliance within 30 minutes." },
      { step: 3, title: "GDRFA / ICP Submission", desc: "Your application is lodged directly through government immigration channels." },
      { step: 4, title: "E-Visa Delivery", desc: "Approved electronic visa is sent directly to your email and WhatsApp for immediate travel." },
    ],
    faqs: [
      { q: "How quickly can I get an urgent Dubai visa?", a: "With our Express Fast-Track service, Dubai e-visas can be approved in as little as 4 to 8 working hours on government business days." },
      { q: "Is travel insurance mandatory for UAE tourist visas?", a: "Yes, all UAE tourist visas issued through Karnish include mandatory COVID & emergency medical travel insurance coverage." },
      { q: "Can my 30-day UAE visa be extended without exiting the country?", a: "Yes, 30 and 60-day tourist visas can be extended inside the UAE for an additional 30 days without airport exit. Contact our visa desk before your visa expiry." },
      { q: "Do women under 25 require special clearance?", a: "Solo female travelers under 25 may be requested by immigration to provide a letter of consent from parents or proof of employment." },
    ],
  },
  {
    slug: "schengen",
    alias: ["europe", "france", "germany", "italy", "switzerland"],
    country: "Schengen (Europe - 29 Countries)",
    title: "Schengen Tourist & Business Visa",
    region: "Europe",
    flag: "🇪🇺",
    image: "/images/destination-03.jpg",
    badge: "Complete File Preparation",
    tagline: "Comprehensive dossier preparation, VFS/BLS appointment scheduling, and itinerary documentation for 29 European countries.",
    startingPrice: 13500,
    startingPriceEUR: 150,
    processingTime: "10 – 15 Working Days",
    validity: "Up to 90 Days (or 1–5 Years Multi)",
    stayPeriod: "Up to 90 Days in any 180-day window",
    entryType: "Single, Double & Multiple Entry",
    approvalRate: "98.7%",
    expressAvailable: false,
    expressTime: "Standard embassy timeline",
    types: [
      {
        id: "schengen-tourist-short",
        name: "Standard Tourist Visa (Type C)",
        validity: "Based on travel plan (up to 90 days)",
        stay: "Up to 90 Days",
        fee: 13500,
        description: "Covers vacations, family holidays, road trips across France, Switzerland, Italy, Spain, Germany, Austria, etc.",
      },
      {
        id: "schengen-business",
        name: "Business & Conference Visa",
        validity: "Up to 6 Months",
        stay: "Up to 90 Days",
        fee: 14800,
        description: "For corporate meetings, trade fairs, client negotiations, and symposiums.",
      },
      {
        id: "schengen-multi-long",
        name: "Multi-Year Schengen Visa Assistance",
        validity: "1 to 5 Years",
        stay: "90 Days in 180 Days",
        fee: 17500,
        description: "For frequent European voyagers with proven Schengen travel history seeking long-term multiple entry stickers.",
      },
    ],
    eligibility: [
      "Passport issued within the last 10 years with at least 2 blank pages and 3 months validity beyond intended EU departure.",
      "Clear financial stability with personal bank statements covering last 6 months (healthy closing balance).",
      "Consistent employment or registered business ownership.",
      "Travel insurance with minimum €30,000 emergency medical and repatriation coverage.",
      "Clean travel history and realistic day-by-day European itinerary.",
    ],
    documents: [
      {
        category: "Financial Proof",
        items: [
          "Original 6 months personal bank statements with bank seal and signature.",
          "Last 3 years Income Tax Returns (ITR-V) or Form 16.",
          "Last 3 months salary slips with official company seal.",
          "Property deeds or investment certificates (optional but enhances profile).",
        ],
      },
      {
        category: "Employment & Professional",
        items: [
          "Official No Objection Certificate (NOC) / Leave Approval letter on employer letterhead.",
          "Company ID card copy.",
          "For self-employed: Business registration / GST certificate, company bank statement (6 months) and company ITR.",
        ],
      },
      {
        category: "Travel Itinerary & Accommodations",
        items: [
          "Day-by-day detailed cover letter with travel itinerary prepared by Karnish experts.",
          "Confirmed flight reservations with PNR.",
          "Hotel vouchers covering every night across all Schengen member states.",
          "Schengen-compliant travel medical insurance (€30,000 minimum).",
        ],
      },
    ],
    steps: [
      { step: 1, title: "Profile Evaluation & Strategy", desc: "We evaluate your financial papers, travel dates, and select the optimal Schengen consulate for highest approval." },
      { step: 2, title: "Dossier Formulation", desc: "Our specialists draft your professional cover letter, hotel reservations, flight routing, and compliant insurance." },
      { step: 3, title: "VFS / TLS / BLS Appointment", desc: "We secure the earliest biometric appointment date at your preferred visa application center." },
      { step: 4, title: "Biometrics & Passport Collection", desc: "You attend biometrics with your pre-organized file. Passport is dispatched safely to your home upon sticker stamping." },
    ],
    faqs: [
      { q: "Which Schengen country should I apply through?", a: "Under Schengen rules, you must apply to the country where you will spend the maximum number of nights, or your primary port of entry if duration is equal." },
      { q: "How much bank balance is recommended for Schengen approval?", a: "Consulates typically recommend a liquid balance of roughly €100 per day of stay plus estimated flight and hotel expenses, with healthy consistent transactions." },
      { q: "Can Karnish help with early VFS appointment slots?", a: "Yes, our automated tracking monitors consular slot openings 24/7 to secure expedited appointment dates when regular calendars are booked out." },
    ],
  },
  {
    slug: "usa",
    alias: ["us", "america"],
    country: "United States of America",
    title: "USA B1/B2 Visitor Visa",
    region: "Americas",
    flag: "🇺🇸",
    image: "/images/destination-02.jpg",
    badge: "10-Year Multiple Entry",
    tagline: "End-to-end DS-160 filing, emergency slot tracking, mock consular interview training, and documentation guidance.",
    startingPrice: 19500,
    startingPriceUSD: 235,
    processingTime: "Dependent on US Embassy Slots",
    validity: "10 Years Multiple Entry",
    stayPeriod: "Up to 6 Months per entry",
    entryType: "Multiple Entry",
    approvalRate: "97.4%",
    expressAvailable: true,
    expressTime: "Emergency appointment facilitation",
    types: [
      {
        id: "usa-b1-b2",
        name: "B1/B2 Tourist & Business Visa",
        validity: "10 Years",
        stay: "Up to 180 Days per visit",
        fee: 19500,
        description: "The gold standard 10-year multi-entry visa for holidaying, visiting relatives, tourism, and attending conferences.",
      },
      {
        id: "usa-interview-waiver",
        name: "Interview Waiver (Dropbox Renewal)",
        validity: "10 Years",
        stay: "Up to 180 Days",
        fee: 14500,
        description: "For travelers renewing a prior US visa within 48 months of expiry without needing an in-person interview.",
      },
    ],
    eligibility: [
      "Demonstrated strong social, economic, and family ties to your home country to satisfy INA Section 214(b).",
      "Clear lawful purpose of visit (leisure, family reunion, conference, medical evaluation).",
      "Sufficient funds to cover all trip expenditures without unauthorized employment in the USA.",
      "Clean criminal and immigration record globally.",
    ],
    documents: [
      {
        category: "US Consular Form Requirements",
        items: [
          "Accurately populated and submitted Form DS-160 with barcode confirmation page.",
          "US visa specification digital photo (2x2 inches / 51x51mm, square, white backdrop).",
          "MRV fee receipt generated through US Travel Docs.",
        ],
      },
      {
        category: "Supporting Dossier for Interview",
        items: [
          "Current original passport and all prior expired passports with international travel stamps.",
          "Employment proof / business credentials and salary slips (last 6 months).",
          "Personal income tax returns (last 3 financial years).",
          "Bank statement with 6-month transaction ledger.",
          "Invitation letter from host in USA with their visa/Green Card copy (if visiting family).",
        ],
      },
    ],
    steps: [
      { step: 1, title: "Detailed DS-160 Filing", desc: "Our US visa attorneys review your complete employment and travel background to eliminate discrepancies." },
      { step: 2, title: "Fee Payment & Slot Booking", desc: "We schedule your Biometric OFC and Consular Interview slots with continuous priority monitoring." },
      { step: 3, title: "1-on-1 Mock Interview Session", desc: "Our senior counselors simulate the consular officer interview, training you on crisp, confident, and truthful answers." },
      { step: 4, title: "Consular Interview & Stamping", desc: "You attend your interview with your tailored dossier. Passport is stamped with a 10-year visa." },
    ],
    faqs: [
      { q: "What is the biggest factor for US visa approval?", a: "Demonstrating strong ties to your home country (job stability, assets, family commitments) and answering consular questions concisely with confidence." },
      { q: "Can I bring documents inside the US consulate?", a: "Yes, physical document folders are allowed, while mobile phones and electronic equipment must be stored in secure lockers outside." },
      { q: "How long is the US B1/B2 visa valid once approved?", a: "For Indian and most international citizens, US B1/B2 visas are granted for 10 years with unlimited multiple entries." },
    ],
  },
  {
    slug: "uk",
    alias: ["britain", "london", "united-kingdom"],
    country: "United Kingdom",
    title: "UK Standard Visitor Visa",
    region: "Europe",
    flag: "🇬🇧",
    image: "/images/destination-01.jpg",
    badge: "2, 5 & 10 Year Options",
    tagline: "Professional UKVI portal filing, financial tie structuring, priority service booking, and VFS biometric appointment guidance.",
    startingPrice: 15900,
    startingPriceGBP: 145,
    processingTime: "15 Working Days (5-Day Priority Available)",
    validity: "6 Months, 2 Years, 5 Years or 10 Years",
    stayPeriod: "Up to 6 Months per visit",
    entryType: "Multiple Entry",
    approvalRate: "98.9%",
    expressAvailable: true,
    expressTime: "5 Working Days (Super Priority: 24h)",
    types: [
      {
        id: "uk-6m-standard",
        name: "Standard Visitor Visa (6 Months)",
        validity: "6 Months",
        stay: "Up to 180 Days",
        fee: 15900,
        description: "The classic UK entry visa for holidays across London, Scotland, Wales, and Northern Ireland.",
      },
      {
        id: "uk-2y-long",
        name: "Long-Term Visitor Visa (2 Years)",
        validity: "2 Years",
        stay: "180 Days per visit",
        fee: 38500,
        description: "Designed for voyagers with regular family or corporate commitments in the United Kingdom.",
      },
      {
        id: "uk-5y-10y",
        name: "Long-Term Visitor Visa (5 or 10 Years)",
        validity: "5 to 10 Years",
        stay: "180 Days per visit",
        fee: 68000,
        description: "Elite multi-year multiple entry visa for high-net-worth investors, executives, and frequent UK visitors.",
      },
    ],
    eligibility: [
      "Demonstrate genuine visitor intent with plans to leave the UK at the end of the stated period.",
      "Clear paper trail explaining source of funds and personal disposable income.",
      "No reliance on public funds or unauthorized work in the UK.",
      "Valid passport with at least 6 months validity.",
    ],
    documents: [
      {
        category: "Financial Provenance (UKVI Standard)",
        items: [
          "6 months bank statements with clear salary / dividend credits.",
          "Explanation for any large, irregular bank deposits (UKVI scrutinizes unexplained credits).",
          "Last 3 years Tax returns / Form 16.",
        ],
      },
      {
        category: "Employment & Identity",
        items: [
          "Employment letter confirming position, salary, start date, and approved leave of absence.",
          "Pay slips covering previous 6 months.",
          "Tenancy, homeownership, or family ties proof.",
        ],
      },
    ],
    steps: [
      { step: 1, title: "UKVI Online Submission", desc: "Detailed form completion on the official UK Visas and Immigration portal." },
      { step: 2, title: "Document Upload & Indexing", desc: "We scan, certify, and upload all documents onto the VFS Global document hub." },
      { step: 3, title: "Biometric Appointment", desc: "You provide fingerprints and digital photo at your designated VFS UK center." },
      { step: 4, title: "Passport Stamping & Return", desc: "Passport is couriered securely back to you with the vignette visa stamped." },
    ],
    faqs: [
      { q: "Why do UK visas get refused?", a: "The #1 reason for UK visa refusal is unexplained funds or cash deposits in bank accounts without clear documented proof of origin. Karnish audits every transaction to ensure total compliance." },
      { q: "Is Priority processing available for UK visas?", a: "Yes, UKVI offers a 5-day Priority service and a next-day Super Priority service in select VFS centers." },
    ],
  },
  {
    slug: "canada",
    alias: ["ca"],
    country: "Canada",
    title: "Canada Visitor Visa (TRV / V-1)",
    region: "Americas",
    flag: "🇨🇦",
    image: "/images/destination-02.jpg",
    badge: "Passport Validity Duration",
    tagline: "IRCC portal file composition, travel history representation, family sponsorship compilation, and biometrics handling.",
    startingPrice: 16800,
    startingPriceCAD: 260,
    processingTime: "20 – 35 Working Days",
    validity: "Up to 10 Years (or until passport expiry)",
    stayPeriod: "Up to 6 Months per visit",
    entryType: "Multiple Entry",
    approvalRate: "96.8%",
    expressAvailable: false,
    expressTime: "Standard IRCC processing",
    types: [
      {
        id: "canada-trv-tourist",
        name: "Temporary Resident Visa (V-1 Tourist)",
        validity: "Up to Passport Expiry (up to 10 Yrs)",
        stay: "Up to 180 Days per entry",
        fee: 16800,
        description: "Explore Banff, Vancouver, Toronto, Niagara Falls, and visit family across Canadian provinces.",
      },
      {
        id: "canada-super-visa",
        name: "Parents & Grandparents Super Visa Support",
        validity: "Up to 10 Years",
        stay: "Up to 5 Years continuous",
        fee: 28500,
        description: "Special multi-entry pathway allowing parents and grandparents of Canadian citizens to stay for up to 5 continuous years.",
      },
    ],
    eligibility: [
      "Demonstrate sufficient financial resources to maintain self and family members in Canada.",
      "Clear intent to return home upon conclusion of authorized stay.",
      "Pass Canadian medical and security checks.",
      "Valid passport for the complete intended duration.",
    ],
    documents: [
      {
        category: "Financial & Employment Portfolio",
        items: [
          "6 months bank statements with strong closing balance.",
          "Employment contract, pay stubs, and approved leave certificate.",
          "Property evaluation, investment statements, or fixed deposits.",
        ],
      },
      {
        category: "Canada Connections (If visiting relatives)",
        items: [
          "Letter of invitation with host's Canada PR card / Canadian passport.",
          "Host's Notice of Assessment (NOA) and T4 tax slips.",
        ],
      },
    ],
    steps: [
      { step: 1, title: "IRCC Profile Building", desc: "We structure your profile inside the official IRCC portal with comprehensive cover letters." },
      { step: 2, title: "Document Certifications", desc: "Digital compression, translation, and verification of all bank and employment papers." },
      { step: 3, title: "Biometrics Instruction Letter (BIL)", desc: "We book your biometric submission at VFS Canada." },
      { step: 4, title: "Passport Submission (PPR)", desc: "Upon approval, your passport is submitted for the physical visa foil counterfoil." },
    ],
    faqs: [
      { q: "How long is a Canada tourist visa usually valid?", a: "Canada typically grants multiple-entry visitor visas for the full remaining validity of your current passport (up to 10 years)." },
      { q: "Do I need medical examination for a Canada tourist visa?", a: "Standard tourist visits under 6 months usually do not require medicals unless staying longer or having lived in specific health-monitored regions." },
    ],
  },
  {
    slug: "australia",
    alias: ["aus", "sydney"],
    country: "Australia",
    title: "Australia Visitor Visa (Subclass 600)",
    region: "Asia Pacific",
    flag: "🇦🇺",
    image: "/images/destination-03.jpg",
    badge: "100% Digital e-Visa",
    tagline: "Direct ImmiAccount portal lodgement, GTE (Genuine Temporary Entrant) justification, and multi-year visa management.",
    startingPrice: 17200,
    startingPriceAUD: 290,
    processingTime: "15 – 25 Working Days",
    validity: "Up to 12 Months (or 3 Years Multi)",
    stayPeriod: "3, 6, or 12 Months per visit",
    entryType: "Single or Multiple Entry",
    approvalRate: "98.2%",
    expressAvailable: true,
    expressTime: "Fast-track lodgement available",
    types: [
      {
        id: "aus-subclass-600-tourist",
        name: "Tourist Stream (Subclass 600)",
        validity: "Up to 12 Months",
        stay: "3 Months per entry",
        fee: 17200,
        description: "Perfect for exploring the Great Barrier Reef, Sydney, Melbourne, and the Gold Coast.",
      },
      {
        id: "aus-family-sponsored",
        name: "Sponsored Family Stream",
        validity: "Up to 12 Months",
        stay: "Up to 6 Months",
        fee: 19800,
        description: "For travelers visiting children or siblings who are Australian citizens or permanent residents.",
      },
    ],
    eligibility: [
      "Meet Genuine Temporary Entrant (GTE) criteria demonstrating that you will abide by visa conditions.",
      "Access to adequate funds for self-support during the Australian trip.",
      "Pass character criteria with zero serious convictions.",
      "Health insurance recommended for the duration of stay.",
    ],
    documents: [
      {
        category: "ImmiAccount Submission Documents",
        items: [
          "Color scanned bio-pages of passport with travel stamps.",
          "National ID (Aadhaar / Voter ID / PAN).",
          "6 months bank statements with certified bank seal.",
          "Income Tax Returns (ITR) for last 3 years.",
        ],
      },
      {
        category: "Professional Standing",
        items: [
          "Leave sanction letter from company on official letterhead.",
          "Latest 3 months salary certificates.",
          "Business incorporation certificate if self-employed.",
        ],
      },
    ],
    steps: [
      { step: 1, title: "GTE & Profile Structuring", desc: "Our Australian visa experts draft an airtight statement of purpose satisfying immigration criteria." },
      { step: 2, title: "Department of Home Affairs Lodgement", desc: "Lodge your file directly into the Australian ImmiAccount portal." },
      { step: 3, title: "Biometric Collection", desc: "Visit VFS Australian Biometric Collection Centre for fingerprinting and photo." },
      { step: 4, title: "Electronic Visa Grant Notice", desc: "Receive your official Subclass 600 Visa Grant Letter directly via email." },
    ],
    faqs: [
      { q: "Is physical passport stamping needed for Australia?", a: "No, Australia issues 100% electronic visas. Your visa grant notice is linked digitally to your passport number in airline and border systems." },
      { q: "Can I work in Australia on a Subclass 600 visa?", a: "No, visitor visas strictly prohibit paid employment in Australia." },
    ],
  },
  {
    slug: "singapore",
    alias: ["sg"],
    country: "Singapore",
    title: "Singapore e-Visa (Entry Visa)",
    region: "Asia Pacific",
    flag: "🇸🇬",
    image: "/images/destination-01.jpg",
    badge: "Fast 3–5 Day Processing",
    tagline: "Authorized ICA submission through accredited visa agents, paperless e-Visa delivery, and travel card guidance.",
    startingPrice: 3899,
    startingPriceSGD: 65,
    processingTime: "3 – 5 Working Days",
    validity: "30 Days to 2 Years Multiple",
    stayPeriod: "Up to 30 Days per entry",
    entryType: "Multiple Entry",
    approvalRate: "99.2%",
    expressAvailable: true,
    expressTime: "24 – 48 Hours",
    types: [
      {
        id: "sg-evisa-standard",
        name: "Standard Tourist e-Visa",
        validity: "Up to 2 Years Multiple Entry",
        stay: "Up to 30 Days per trip",
        fee: 3899,
        description: "Official authorized ICA electronic visa for Marina Bay, Sentosa Island, and shopping getaways.",
      },
      {
        id: "sg-evisa-express",
        name: "Express Urgent e-Visa",
        validity: "Up to 2 Years Multiple Entry",
        stay: "Up to 30 Days",
        fee: 5999,
        description: "Expedited lodgement for emergency travel, business summits, or last-minute flight bookings.",
      },
    ],
    eligibility: [
      "Passport valid for minimum 6 months beyond date of arrival in Singapore.",
      "Clear front & back bio-page scans.",
      "Recent passport-style photograph matching Singapore ICA specifications (matte finish, white background).",
      "Confirmed round-trip flights and hotel bookings.",
    ],
    documents: [
      {
        category: "ICA Mandatory Papers",
        items: [
          "Passport copy (first page, last page, and any observation pages).",
          "Form 14A duly signed by traveler.",
          "Passport photograph: 35mm x 45mm, borderless, semi-matte or matte finish, white background.",
        ],
      },
      {
        category: "Travel Confirmations",
        items: [
          "Confirmed return flight booking with airline ticket number.",
          "Confirmed hotel reservation or Singapore citizen/PR Invitation Letter (Form V39A).",
          "6 months bank statement showing adequate travel liquidity.",
        ],
      },
    ],
    steps: [
      { step: 1, title: "Document Upload", desc: "Submit passport scans, ICA compliant photo, and flight details online." },
      { step: 2, title: "Authorized Agent Verification", desc: "Karnish checks Form 14A details and submits directly into the ICA SAVE portal." },
      { step: 3, title: "ICA Approval", desc: "Singapore Immigration and Checkpoints Authority processes and approves the e-Visa." },
      { step: 4, title: "E-Visa PDF Download", desc: "Your e-Visa with security QR code is emailed to you. Simply print and fly." },
    ],
    faqs: [
      { q: "How long does a Singapore e-Visa remain valid?", a: "Singapore typically issues multiple-entry visas valid for up to 2 years, allowing up to 30 days of stay on each entry." },
      { q: "Do I also need the SG Arrival Card?", a: "Yes, all visitors must submit the free SG Arrival Card (SGAC) with electronic health declaration within 3 days prior to arrival. Our team assists you with this automatically." },
    ],
  },
];

export const VISA_DESTINATIONS = ALL_VISA_DESTINATIONS.slice(0, 3);

export function getVisa(slug) {
  const clean = String(slug || "").toLowerCase().trim();
  return VISA_DESTINATIONS.find(
    (v) => v.slug === clean || (v.alias && v.alias.includes(clean))
  );
}

export function getAllVisaSlugs() {
  return VISA_DESTINATIONS.map((v) => v.slug);
}
